// Copyright 2026 Benjamin Grewell
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.2
// source: proto/loom/v1/control.proto

package loomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FlowRole is what a configured flow does. UNSPECIFIED is treated as SENDER, so
// an unset role defaults to sending.
type FlowRole int32

const (
	FlowRole_FLOW_ROLE_UNSPECIFIED FlowRole = 0
	FlowRole_FLOW_ROLE_SENDER      FlowRole = 1
	FlowRole_FLOW_ROLE_RECEIVER    FlowRole = 2 // binds an ephemeral port and drains+accounts inbound
	FlowRole_FLOW_ROLE_REFLECTOR   FlowRole = 3 // echoes received packets (not yet implemented)
	// Request/response pair for emulations that need real bidirectional traffic
	// (e.g. https-browse): the responder binds an ephemeral port and serves the
	// bytes a requester asks for; the requester drives the behavior script.
	FlowRole_FLOW_ROLE_RESPONDER FlowRole = 4 // binds an ephemeral port, serves requested bytes
	FlowRole_FLOW_ROLE_REQUESTER FlowRole = 5 // drives a script, requesting objects from a responder
	// Application pair for real protocol engines (core/app): the server binds an
	// ephemeral port (returned as ConfigureResponse.data_port) and runs the far
	// end of the app named in FlowSpec.app; the client drives that app toward it.
	FlowRole_FLOW_ROLE_APP_CLIENT FlowRole = 6 // drives the named app's client engine at an app server
	FlowRole_FLOW_ROLE_APP_SERVER FlowRole = 7 // binds an ephemeral port, runs the named app's server engine
)

// Enum value maps for FlowRole.
var (
	FlowRole_name = map[int32]string{
		0: "FLOW_ROLE_UNSPECIFIED",
		1: "FLOW_ROLE_SENDER",
		2: "FLOW_ROLE_RECEIVER",
		3: "FLOW_ROLE_REFLECTOR",
		4: "FLOW_ROLE_RESPONDER",
		5: "FLOW_ROLE_REQUESTER",
		6: "FLOW_ROLE_APP_CLIENT",
		7: "FLOW_ROLE_APP_SERVER",
	}
	FlowRole_value = map[string]int32{
		"FLOW_ROLE_UNSPECIFIED": 0,
		"FLOW_ROLE_SENDER":      1,
		"FLOW_ROLE_RECEIVER":    2,
		"FLOW_ROLE_REFLECTOR":   3,
		"FLOW_ROLE_RESPONDER":   4,
		"FLOW_ROLE_REQUESTER":   5,
		"FLOW_ROLE_APP_CLIENT":  6,
		"FLOW_ROLE_APP_SERVER":  7,
	}
)

func (x FlowRole) Enum() *FlowRole {
	p := new(FlowRole)
	*p = x
	return p
}

func (x FlowRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_loom_v1_control_proto_enumTypes[0].Descriptor()
}

func (FlowRole) Type() protoreflect.EnumType {
	return &file_proto_loom_v1_control_proto_enumTypes[0]
}

func (x FlowRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowRole.Descriptor instead.
func (FlowRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // human-readable build version
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	ApiVersion    uint32                 `protobuf:"varint,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"` // control-plane wire version the agent speaks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	ApiVersion    uint32                 `protobuf:"varint,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"` // wire version the controller speaks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegisterRequest) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{4}
}

type CapabilitiesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Datapaths          []string               `protobuf:"bytes,1,rep,name=datapaths,proto3" json:"datapaths,omitempty"`
	Generators         []string               `protobuf:"bytes,2,rep,name=generators,proto3" json:"generators,omitempty"`
	Schedulers         []string               `protobuf:"bytes,3,rep,name=schedulers,proto3" json:"schedulers,omitempty"`
	Payloads           []string               `protobuf:"bytes,4,rep,name=payloads,proto3" json:"payloads,omitempty"`
	HardwareTimestamps bool                   `protobuf:"varint,5,opt,name=hardware_timestamps,json=hardwareTimestamps,proto3" json:"hardware_timestamps,omitempty"`
	// Registered netpath network names (e.g. "host"). Consumers check networks
	// and apps at provision time and fail fast on version skew; all additions
	// are additive per ADR-0021, so mixed versions degrade to clean refusals.
	Networks []string `protobuf:"bytes,6,rep,name=networks,proto3" json:"networks,omitempty"`
	// Registered app names (e.g. "voip"), same skew-gate contract as networks.
	// This is the UNION of the client- and server-side registries, kept for
	// consumers predating the per-side lists below.
	Apps []string `protobuf:"bytes,7,rep,name=apps,proto3" json:"apps,omitempty"`
	// Per-side app registry names: what this agent can run as APP_CLIENT and as
	// APP_SERVER respectively. A slimmed build carrying only one side of an app
	// advertises it on that side only, so a controller refuses placing the
	// missing side at provision time instead of failing downstream at Configure.
	// Absent on agents predating these fields — consumers fall back to `apps`.
	AppsClient    []string `protobuf:"bytes,8,rep,name=apps_client,json=appsClient,proto3" json:"apps_client,omitempty"`
	AppsServer    []string `protobuf:"bytes,9,rep,name=apps_server,json=appsServer,proto3" json:"apps_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilitiesResponse) GetDatapaths() []string {
	if x != nil {
		return x.Datapaths
	}
	return nil
}

func (x *CapabilitiesResponse) GetGenerators() []string {
	if x != nil {
		return x.Generators
	}
	return nil
}

func (x *CapabilitiesResponse) GetSchedulers() []string {
	if x != nil {
		return x.Schedulers
	}
	return nil
}

func (x *CapabilitiesResponse) GetPayloads() []string {
	if x != nil {
		return x.Payloads
	}
	return nil
}

func (x *CapabilitiesResponse) GetHardwareTimestamps() bool {
	if x != nil {
		return x.HardwareTimestamps
	}
	return false
}

func (x *CapabilitiesResponse) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *CapabilitiesResponse) GetApps() []string {
	if x != nil {
		return x.Apps
	}
	return nil
}

func (x *CapabilitiesResponse) GetAppsClient() []string {
	if x != nil {
		return x.AppsClient
	}
	return nil
}

func (x *CapabilitiesResponse) GetAppsServer() []string {
	if x != nil {
		return x.AppsServer
	}
	return nil
}

// FlowSpec describes one flow to run, mirroring `loom run` flags.
type FlowSpec struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Generator  string                 `protobuf:"bytes,1,opt,name=generator,proto3" json:"generator,omitempty"`
	Payload    string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Datapath   string                 `protobuf:"bytes,3,opt,name=datapath,proto3" json:"datapath,omitempty"`
	Target     string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"` // host:port for udp/tcp
	PacketSize uint32                 `protobuf:"varint,5,opt,name=packet_size,json=packetSize,proto3" json:"packet_size,omitempty"`
	Rate       string                 `protobuf:"bytes,6,opt,name=rate,proto3" json:"rate,omitempty"`    // e.g. "100Mbps"; empty = unlimited
	Iface      string                 `protobuf:"bytes,7,opt,name=iface,proto3" json:"iface,omitempty"`  // NIC name for the afxdp datapath
	Queue      uint32                 `protobuf:"varint,8,opt,name=queue,proto3" json:"queue,omitempty"` // NIC queue for the afxdp datapath
	// emulation names an application-behavior emulation (e.g. "voip-call",
	// "https-browse"); empty = a raw flow. params are its tuning knobs.
	Emulation string `protobuf:"bytes,9,opt,name=emulation,proto3" json:"emulation,omitempty"`
	// Stop condition (whichever is reached first; all empty = until-stopped).
	Duration *durationpb.Duration `protobuf:"bytes,10,opt,name=duration,proto3" json:"duration,omitempty"`
	Count    uint64               `protobuf:"varint,11,opt,name=count,proto3" json:"count,omitempty"`                                                                            // packets
	Volume   uint64               `protobuf:"varint,12,opt,name=volume,proto3" json:"volume,omitempty"`                                                                          // bytes
	Params   map[string]string    `protobuf:"bytes,13,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // emulation parameters
	Seed     int64                `protobuf:"varint,14,opt,name=seed,proto3" json:"seed,omitempty"`                                                                              // RNG seed for reproducible emulated shapes
	// transport carries request/response emulations (FLOW_ROLE_REQUESTER /
	// FLOW_ROLE_RESPONDER): "tcp" or "udp". Ignored by other roles, which use the
	// datapath field instead.
	Transport string `protobuf:"bytes,15,opt,name=transport,proto3" json:"transport,omitempty"`
	// app names the application protocol engine for FLOW_ROLE_APP_CLIENT /
	// FLOW_ROLE_APP_SERVER: "voip" | "http" | "video". Ignored by other roles.
	App string `protobuf:"bytes,16,opt,name=app,proto3" json:"app,omitempty"`
	// network selects the netpath network the app's sockets are opened on;
	// "" = "host" (the OS network stack).
	Network string `protobuf:"bytes,17,opt,name=network,proto3" json:"network,omitempty"`
	// local is the local address to bind for datapath-backed networks (e.g. the
	// UE address on a gVisor netstack); "" lets the network choose.
	Local string `protobuf:"bytes,18,opt,name=local,proto3" json:"local,omitempty"`
	// role selects sender vs receiver (and, later, reflector). A receiver binds an
	// ephemeral UDP port returned as ConfigureResponse.data_port and
	// drains+accounts inbound packets instead of generating.
	Role          FlowRole `protobuf:"varint,21,opt,name=role,proto3,enum=loom.v1.FlowRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowSpec) Reset() {
	*x = FlowSpec{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSpec) ProtoMessage() {}

func (x *FlowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSpec.ProtoReflect.Descriptor instead.
func (*FlowSpec) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *FlowSpec) GetGenerator() string {
	if x != nil {
		return x.Generator
	}
	return ""
}

func (x *FlowSpec) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *FlowSpec) GetDatapath() string {
	if x != nil {
		return x.Datapath
	}
	return ""
}

func (x *FlowSpec) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FlowSpec) GetPacketSize() uint32 {
	if x != nil {
		return x.PacketSize
	}
	return 0
}

func (x *FlowSpec) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *FlowSpec) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *FlowSpec) GetQueue() uint32 {
	if x != nil {
		return x.Queue
	}
	return 0
}

func (x *FlowSpec) GetEmulation() string {
	if x != nil {
		return x.Emulation
	}
	return ""
}

func (x *FlowSpec) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *FlowSpec) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FlowSpec) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *FlowSpec) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *FlowSpec) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *FlowSpec) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *FlowSpec) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *FlowSpec) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *FlowSpec) GetLocal() string {
	if x != nil {
		return x.Local
	}
	return ""
}

func (x *FlowSpec) GetRole() FlowRole {
	if x != nil {
		return x.Role
	}
	return FlowRole_FLOW_ROLE_UNSPECIFIED
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flow          *FlowSpec              `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureRequest) GetFlow() *FlowSpec {
	if x != nil {
		return x.Flow
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	DataPort      uint32                 `protobuf:"varint,2,opt,name=data_port,json=dataPort,proto3" json:"data_port,omitempty"` // ephemeral port the agent will listen/send on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ConfigureResponse) GetDataPort() uint32 {
	if x != nil {
		return x.DataPort
	}
	return 0
}

type ArmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmRequest) Reset() {
	*x = ArmRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmRequest) ProtoMessage() {}

func (x *ArmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmRequest.ProtoReflect.Descriptor instead.
func (*ArmRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ArmRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type ArmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmResponse) Reset() {
	*x = ArmResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmResponse) ProtoMessage() {}

func (x *ArmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmResponse.ProtoReflect.Descriptor instead.
func (*ArmResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{10}
}

type StartRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	FlowId string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	// start_at_unix_nanos schedules the flow to begin at an absolute time on the
	// agent's own clock (the controller translates a shared target time into each
	// agent's clock using the TimeSync offset, so flows on different hosts begin in
	// lockstep regardless of link latency). 0 (or a past time) starts immediately.
	StartAtUnixNanos int64 `protobuf:"varint,2,opt,name=start_at_unix_nanos,json=startAtUnixNanos,proto3" json:"start_at_unix_nanos,omitempty"`
	// report_interval_nanos is the reporting interval I. The agent emits one
	// telemetry sample per interval boundary at start_at + k*I (anchored to the
	// gate, or to first run when start_at is 0), each carrying that interval's
	// delta. 0 = legacy free-running cadence (back-compat with older controllers).
	ReportIntervalNanos int64 `protobuf:"varint,3,opt,name=report_interval_nanos,json=reportIntervalNanos,proto3" json:"report_interval_nanos,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *StartRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *StartRequest) GetStartAtUnixNanos() int64 {
	if x != nil {
		return x.StartAtUnixNanos
	}
	return 0
}

func (x *StartRequest) GetReportIntervalNanos() int64 {
	if x != nil {
		return x.ReportIntervalNanos
	}
	return 0
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{12}
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *StopRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{14}
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *DestroyRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{16}
}

// TimeSync four-timestamp exchange: client stamps t1, server stamps t2 (recv)
// and t3 (send), client stamps t4 on receipt.
type TimeSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T1            int64                  `protobuf:"varint,1,opt,name=t1,proto3" json:"t1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSyncRequest) Reset() {
	*x = TimeSyncRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncRequest) ProtoMessage() {}

func (x *TimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncRequest.ProtoReflect.Descriptor instead.
func (*TimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *TimeSyncRequest) GetT1() int64 {
	if x != nil {
		return x.T1
	}
	return 0
}

type TimeSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T1            int64                  `protobuf:"varint,1,opt,name=t1,proto3" json:"t1,omitempty"`
	T2            int64                  `protobuf:"varint,2,opt,name=t2,proto3" json:"t2,omitempty"`
	T3            int64                  `protobuf:"varint,3,opt,name=t3,proto3" json:"t3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSyncResponse) Reset() {
	*x = TimeSyncResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncResponse) ProtoMessage() {}

func (x *TimeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncResponse.ProtoReflect.Descriptor instead.
func (*TimeSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *TimeSyncResponse) GetT1() int64 {
	if x != nil {
		return x.T1
	}
	return 0
}

func (x *TimeSyncResponse) GetT2() int64 {
	if x != nil {
		return x.T2
	}
	return 0
}

func (x *TimeSyncResponse) GetT3() int64 {
	if x != nil {
		return x.T3
	}
	return 0
}

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"` // empty = all flows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *TelemetryRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type TelemetrySample struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	FlowId     string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Nanos      int64                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`                                // agent timestamp of this reading (the boundary)
	Bytes      uint64                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`                                // cumulative bytes
	Packets    uint64                 `protobuf:"varint,4,opt,name=packets,proto3" json:"packets,omitempty"`                            // cumulative packets
	BitsPerSec float64                `protobuf:"fixed64,5,opt,name=bits_per_sec,json=bitsPerSec,proto3" json:"bits_per_sec,omitempty"` // legacy; the controller computes rate from the delta
	// Interval accounting, anchored to the scheduled-start gate. The agent reads
	// its counters at each boundary start_at + k*I and reports the interval's delta,
	// so the controller is a pure summer (no central rate clock).
	IntervalIndex   int64       `protobuf:"varint,6,opt,name=interval_index,json=intervalIndex,proto3" json:"interval_index,omitempty"`       // k: 0 for [T,T+I], 1 for [T+I,T+2I], …; -1 on the final sample
	IntervalBytes   uint64      `protobuf:"varint,7,opt,name=interval_bytes,json=intervalBytes,proto3" json:"interval_bytes,omitempty"`       // delta bytes during interval k
	IntervalPackets uint64      `protobuf:"varint,8,opt,name=interval_packets,json=intervalPackets,proto3" json:"interval_packets,omitempty"` // delta packets during interval k
	IntervalNanos   int64       `protobuf:"varint,9,opt,name=interval_nanos,json=intervalNanos,proto3" json:"interval_nanos,omitempty"`       // measured elapsed ns of interval k (rate = interval_bytes*8/interval_nanos)
	Final           bool        `protobuf:"varint,10,opt,name=final,proto3" json:"final,omitempty"`                                           // true on the completion sample (trailing partial interval)
	Tcp             *TcpInfo    `protobuf:"bytes,11,opt,name=tcp,proto3" json:"tcp,omitempty"`                                                // sender-side TCP_INFO diagnostics (nil for non-TCP datapaths)
	App             *AppMetrics `protobuf:"bytes,12,opt,name=app,proto3" json:"app,omitempty"`                                                // app-layer quality metrics (nil for non-app flows)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TelemetrySample) Reset() {
	*x = TelemetrySample{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySample) ProtoMessage() {}

func (x *TelemetrySample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySample.ProtoReflect.Descriptor instead.
func (*TelemetrySample) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *TelemetrySample) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *TelemetrySample) GetNanos() int64 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

func (x *TelemetrySample) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *TelemetrySample) GetPackets() uint64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *TelemetrySample) GetBitsPerSec() float64 {
	if x != nil {
		return x.BitsPerSec
	}
	return 0
}

func (x *TelemetrySample) GetIntervalIndex() int64 {
	if x != nil {
		return x.IntervalIndex
	}
	return 0
}

func (x *TelemetrySample) GetIntervalBytes() uint64 {
	if x != nil {
		return x.IntervalBytes
	}
	return 0
}

func (x *TelemetrySample) GetIntervalPackets() uint64 {
	if x != nil {
		return x.IntervalPackets
	}
	return 0
}

func (x *TelemetrySample) GetIntervalNanos() int64 {
	if x != nil {
		return x.IntervalNanos
	}
	return 0
}

func (x *TelemetrySample) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *TelemetrySample) GetTcp() *TcpInfo {
	if x != nil {
		return x.Tcp
	}
	return nil
}

func (x *TelemetrySample) GetApp() *AppMetrics {
	if x != nil {
		return x.App
	}
	return nil
}

// AppMetrics carries the per-interval quality metrics of an app flow
// (FLOW_ROLE_APP_CLIENT / FLOW_ROLE_APP_SERVER); the member set matches
// FlowSpec.app.
type AppMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AppMetrics_Voip
	//	*AppMetrics_Http
	//	*AppMetrics_Video
	Kind          isAppMetrics_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppMetrics) Reset() {
	*x = AppMetrics{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMetrics) ProtoMessage() {}

func (x *AppMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMetrics.ProtoReflect.Descriptor instead.
func (*AppMetrics) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{21}
}

func (x *AppMetrics) GetKind() isAppMetrics_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AppMetrics) GetVoip() *VoipMetrics {
	if x != nil {
		if x, ok := x.Kind.(*AppMetrics_Voip); ok {
			return x.Voip
		}
	}
	return nil
}

func (x *AppMetrics) GetHttp() *HttpMetrics {
	if x != nil {
		if x, ok := x.Kind.(*AppMetrics_Http); ok {
			return x.Http
		}
	}
	return nil
}

func (x *AppMetrics) GetVideo() *VideoMetrics {
	if x != nil {
		if x, ok := x.Kind.(*AppMetrics_Video); ok {
			return x.Video
		}
	}
	return nil
}

type isAppMetrics_Kind interface {
	isAppMetrics_Kind()
}

type AppMetrics_Voip struct {
	Voip *VoipMetrics `protobuf:"bytes,1,opt,name=voip,proto3,oneof"`
}

type AppMetrics_Http struct {
	Http *HttpMetrics `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

type AppMetrics_Video struct {
	Video *VideoMetrics `protobuf:"bytes,3,opt,name=video,proto3,oneof"`
}

func (*AppMetrics_Voip) isAppMetrics_Kind() {}

func (*AppMetrics_Http) isAppMetrics_Kind() {}

func (*AppMetrics_Video) isAppMetrics_Kind() {}

// VoipMetrics is the RTP/RTCP receive-side quality snapshot: ITU-T G.107
// E-model scores plus the RFC 3550 statistics they were computed from.
//
// Interval vs cumulative: on boundary samples, loss_pct/discard_pct (and the
// mos_cq/r_factor scored from them) cover only the span since the previous
// boundary — the flow sampler pattern. On the FINAL telemetry sample they are
// scored over the whole call, so the end-of-run summary reflects whole-call
// quality rather than the trailing partial interval. rx_packets, lost, gaps,
// and jitter_ms are cumulative/current on every sample.
type VoipMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MosCq         float64                `protobuf:"fixed64,1,opt,name=mos_cq,json=mosCq,proto3" json:"mos_cq,omitempty"`                      // conversational-quality MOS from r_factor
	RFactor       float64                `protobuf:"fixed64,2,opt,name=r_factor,json=rFactor,proto3" json:"r_factor,omitempty"`                // G.107 R
	JitterMs      float64                `protobuf:"fixed64,3,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`             // RFC 3550 A.8 interarrival jitter (current)
	LossPct       float64                `protobuf:"fixed64,4,opt,name=loss_pct,json=lossPct,proto3" json:"loss_pct,omitempty"`                // network loss percentage (interval; whole-call on final)
	DiscardPct    float64                `protobuf:"fixed64,5,opt,name=discard_pct,json=discardPct,proto3" json:"discard_pct,omitempty"`       // jitter-buffer discard percentage (interval; whole-call on final)
	BurstR        float64                `protobuf:"fixed64,6,opt,name=burst_r,json=burstR,proto3" json:"burst_r,omitempty"`                   // Gilbert burst ratio (1.0 = random loss)
	RttMs         float64                `protobuf:"fixed64,7,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`                      // RFC 3550 §6.4.1 round-trip time
	OwdMs         float64                `protobuf:"fixed64,8,opt,name=owd_ms,json=owdMs,proto3" json:"owd_ms,omitempty"`                      // one-way delay estimate
	OwdErrMs      float64                `protobuf:"fixed64,9,opt,name=owd_err_ms,json=owdErrMs,proto3" json:"owd_err_ms,omitempty"`           // owd error bound (owd.Tracker ErrBound)
	OwdMethod     string                 `protobuf:"bytes,10,opt,name=owd_method,json=owdMethod,proto3" json:"owd_method,omitempty"`           // how owd was obtained (e.g. "timesync", "rtt/2")
	RxPackets     uint64                 `protobuf:"varint,11,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`          // packets received, cumulative over the call
	Lost          uint64                 `protobuf:"varint,12,opt,name=lost,proto3" json:"lost,omitempty"`                                     // packets lost, cumulative over the call (clamped at 0)
	Gaps          []*MediaGap            `protobuf:"bytes,13,rep,name=gaps,proto3" json:"gaps,omitempty"`                                      // loss/gap events, cumulative over the call
	RemoteMosCq   float64                `protobuf:"fixed64,14,opt,name=remote_mos_cq,json=remoteMosCq,proto3" json:"remote_mos_cq,omitempty"` // far end's MOS as reported via RTCP
	Emodel        *EModelBreakdown       `protobuf:"bytes,15,opt,name=emodel,proto3" json:"emodel,omitempty"`                                  // G.107 component breakdown behind r_factor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoipMetrics) Reset() {
	*x = VoipMetrics{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoipMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoipMetrics) ProtoMessage() {}

func (x *VoipMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoipMetrics.ProtoReflect.Descriptor instead.
func (*VoipMetrics) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{22}
}

func (x *VoipMetrics) GetMosCq() float64 {
	if x != nil {
		return x.MosCq
	}
	return 0
}

func (x *VoipMetrics) GetRFactor() float64 {
	if x != nil {
		return x.RFactor
	}
	return 0
}

func (x *VoipMetrics) GetJitterMs() float64 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *VoipMetrics) GetLossPct() float64 {
	if x != nil {
		return x.LossPct
	}
	return 0
}

func (x *VoipMetrics) GetDiscardPct() float64 {
	if x != nil {
		return x.DiscardPct
	}
	return 0
}

func (x *VoipMetrics) GetBurstR() float64 {
	if x != nil {
		return x.BurstR
	}
	return 0
}

func (x *VoipMetrics) GetRttMs() float64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *VoipMetrics) GetOwdMs() float64 {
	if x != nil {
		return x.OwdMs
	}
	return 0
}

func (x *VoipMetrics) GetOwdErrMs() float64 {
	if x != nil {
		return x.OwdErrMs
	}
	return 0
}

func (x *VoipMetrics) GetOwdMethod() string {
	if x != nil {
		return x.OwdMethod
	}
	return ""
}

func (x *VoipMetrics) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *VoipMetrics) GetLost() uint64 {
	if x != nil {
		return x.Lost
	}
	return 0
}

func (x *VoipMetrics) GetGaps() []*MediaGap {
	if x != nil {
		return x.Gaps
	}
	return nil
}

func (x *VoipMetrics) GetRemoteMosCq() float64 {
	if x != nil {
		return x.RemoteMosCq
	}
	return 0
}

func (x *VoipMetrics) GetEmodel() *EModelBreakdown {
	if x != nil {
		return x.Emodel
	}
	return nil
}

// EModelBreakdown exposes the ITU-T G.107 components so an R score is
// auditable: R = ro - is - idte - idle - idd - ie_eff (+ A, not carried).
type EModelBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ro            float64                `protobuf:"fixed64,1,opt,name=ro,proto3" json:"ro,omitempty"`                    // basic signal-to-noise ratio
	Is            float64                `protobuf:"fixed64,2,opt,name=is,proto3" json:"is,omitempty"`                    // simultaneous impairment factor
	Idte          float64                `protobuf:"fixed64,3,opt,name=idte,proto3" json:"idte,omitempty"`                // talker echo delay impairment
	Idle          float64                `protobuf:"fixed64,4,opt,name=idle,proto3" json:"idle,omitempty"`                // listener echo delay impairment
	Idd           float64                `protobuf:"fixed64,5,opt,name=idd,proto3" json:"idd,omitempty"`                  // too-long absolute delay impairment
	IeEff         float64                `protobuf:"fixed64,6,opt,name=ie_eff,json=ieEff,proto3" json:"ie_eff,omitempty"` // effective equipment impairment (codec + loss)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EModelBreakdown) Reset() {
	*x = EModelBreakdown{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EModelBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EModelBreakdown) ProtoMessage() {}

func (x *EModelBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EModelBreakdown.ProtoReflect.Descriptor instead.
func (*EModelBreakdown) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{23}
}

func (x *EModelBreakdown) GetRo() float64 {
	if x != nil {
		return x.Ro
	}
	return 0
}

func (x *EModelBreakdown) GetIs() float64 {
	if x != nil {
		return x.Is
	}
	return 0
}

func (x *EModelBreakdown) GetIdte() float64 {
	if x != nil {
		return x.Idte
	}
	return 0
}

func (x *EModelBreakdown) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *EModelBreakdown) GetIdd() float64 {
	if x != nil {
		return x.Idd
	}
	return 0
}

func (x *EModelBreakdown) GetIeEff() float64 {
	if x != nil {
		return x.IeEff
	}
	return 0
}

// MediaGap is one contiguous loss/stall event in a media stream.
type MediaGap struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartUnixNanos int64                  `protobuf:"varint,1,opt,name=start_unix_nanos,json=startUnixNanos,proto3" json:"start_unix_nanos,omitempty"`
	EndUnixNanos   int64                  `protobuf:"varint,2,opt,name=end_unix_nanos,json=endUnixNanos,proto3" json:"end_unix_nanos,omitempty"`
	PacketsLost    uint32                 `protobuf:"varint,3,opt,name=packets_lost,json=packetsLost,proto3" json:"packets_lost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaGap) Reset() {
	*x = MediaGap{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaGap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaGap) ProtoMessage() {}

func (x *MediaGap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaGap.ProtoReflect.Descriptor instead.
func (*MediaGap) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{24}
}

func (x *MediaGap) GetStartUnixNanos() int64 {
	if x != nil {
		return x.StartUnixNanos
	}
	return 0
}

func (x *MediaGap) GetEndUnixNanos() int64 {
	if x != nil {
		return x.EndUnixNanos
	}
	return 0
}

func (x *MediaGap) GetPacketsLost() uint32 {
	if x != nil {
		return x.PacketsLost
	}
	return 0
}

// HttpMetrics is the requester-side HTTP/TLS quality snapshot.
type HttpMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requests       uint64                 `protobuf:"varint,1,opt,name=requests,proto3" json:"requests,omitempty"`                                      // requests completed this interval
	Errors         uint64                 `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`                                          // failed requests this interval
	TtfbMsP95      float64                `protobuf:"fixed64,3,opt,name=ttfb_ms_p95,json=ttfbMsP95,proto3" json:"ttfb_ms_p95,omitempty"`                // p95 time-to-first-byte
	GoodputMbps    float64                `protobuf:"fixed64,4,opt,name=goodput_mbps,json=goodputMbps,proto3" json:"goodput_mbps,omitempty"`            // application-payload throughput
	TlsHandshakeMs float64                `protobuf:"fixed64,5,opt,name=tls_handshake_ms,json=tlsHandshakeMs,proto3" json:"tls_handshake_ms,omitempty"` // TLS handshake latency
	ConnectMs      float64                `protobuf:"fixed64,6,opt,name=connect_ms,json=connectMs,proto3" json:"connect_ms,omitempty"`                  // TCP connect latency
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HttpMetrics) Reset() {
	*x = HttpMetrics{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpMetrics) ProtoMessage() {}

func (x *HttpMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpMetrics.ProtoReflect.Descriptor instead.
func (*HttpMetrics) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{25}
}

func (x *HttpMetrics) GetRequests() uint64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *HttpMetrics) GetErrors() uint64 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *HttpMetrics) GetTtfbMsP95() float64 {
	if x != nil {
		return x.TtfbMsP95
	}
	return 0
}

func (x *HttpMetrics) GetGoodputMbps() float64 {
	if x != nil {
		return x.GoodputMbps
	}
	return 0
}

func (x *HttpMetrics) GetTlsHandshakeMs() float64 {
	if x != nil {
		return x.TlsHandshakeMs
	}
	return 0
}

func (x *HttpMetrics) GetConnectMs() float64 {
	if x != nil {
		return x.ConnectMs
	}
	return 0
}

// VideoMetrics is the player-side streaming QoE snapshot.
type VideoMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Stalls         uint64                 `protobuf:"varint,1,opt,name=stalls,proto3" json:"stalls,omitempty"`                                          // rebuffer events this interval
	StallTimeMs    float64                `protobuf:"fixed64,2,opt,name=stall_time_ms,json=stallTimeMs,proto3" json:"stall_time_ms,omitempty"`          // total time stalled
	RebufferRatio  float64                `protobuf:"fixed64,3,opt,name=rebuffer_ratio,json=rebufferRatio,proto3" json:"rebuffer_ratio,omitempty"`      // stall_time / (stall_time + play_time)
	BufferMs       float64                `protobuf:"fixed64,4,opt,name=buffer_ms,json=bufferMs,proto3" json:"buffer_ms,omitempty"`                     // current buffer depth
	AvgBitrateKbps float64                `protobuf:"fixed64,5,opt,name=avg_bitrate_kbps,json=avgBitrateKbps,proto3" json:"avg_bitrate_kbps,omitempty"` // average selected bitrate
	StartupMs      float64                `protobuf:"fixed64,6,opt,name=startup_ms,json=startupMs,proto3" json:"startup_ms,omitempty"`                  // time to first frame
	StallEvents    []*MediaGap            `protobuf:"bytes,7,rep,name=stall_events,json=stallEvents,proto3" json:"stall_events,omitempty"`              // individual stall intervals
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoMetrics) Reset() {
	*x = VideoMetrics{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetrics) ProtoMessage() {}

func (x *VideoMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetrics.ProtoReflect.Descriptor instead.
func (*VideoMetrics) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{26}
}

func (x *VideoMetrics) GetStalls() uint64 {
	if x != nil {
		return x.Stalls
	}
	return 0
}

func (x *VideoMetrics) GetStallTimeMs() float64 {
	if x != nil {
		return x.StallTimeMs
	}
	return 0
}

func (x *VideoMetrics) GetRebufferRatio() float64 {
	if x != nil {
		return x.RebufferRatio
	}
	return 0
}

func (x *VideoMetrics) GetBufferMs() float64 {
	if x != nil {
		return x.BufferMs
	}
	return 0
}

func (x *VideoMetrics) GetAvgBitrateKbps() float64 {
	if x != nil {
		return x.AvgBitrateKbps
	}
	return 0
}

func (x *VideoMetrics) GetStartupMs() float64 {
	if x != nil {
		return x.StartupMs
	}
	return 0
}

func (x *VideoMetrics) GetStallEvents() []*MediaGap {
	if x != nil {
		return x.StallEvents
	}
	return nil
}

// TcpInfo carries a snapshot of the sender socket's kernel TCP_INFO, for link
// profiling (is TCP entering a bad state?). Populated only for the TCP datapath
// on the sending side; zero/absent otherwise.
type TcpInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRetrans  uint32                 `protobuf:"varint,1,opt,name=total_retrans,json=totalRetrans,proto3" json:"total_retrans,omitempty"` // cumulative retransmitted segments
	Lost          uint32                 `protobuf:"varint,2,opt,name=lost,proto3" json:"lost,omitempty"`                                     // segments currently considered lost
	RttUs         uint32                 `protobuf:"varint,3,opt,name=rtt_us,json=rttUs,proto3" json:"rtt_us,omitempty"`                      // smoothed round-trip time (microseconds)
	RttvarUs      uint32                 `protobuf:"varint,4,opt,name=rttvar_us,json=rttvarUs,proto3" json:"rttvar_us,omitempty"`             // round-trip time variance (microseconds)
	SndCwnd       uint32                 `protobuf:"varint,5,opt,name=snd_cwnd,json=sndCwnd,proto3" json:"snd_cwnd,omitempty"`                // congestion window (segments)
	SndSsthresh   uint32                 `protobuf:"varint,6,opt,name=snd_ssthresh,json=sndSsthresh,proto3" json:"snd_ssthresh,omitempty"`    // slow-start threshold (segments)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpInfo) Reset() {
	*x = TcpInfo{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpInfo) ProtoMessage() {}

func (x *TcpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpInfo.ProtoReflect.Descriptor instead.
func (*TcpInfo) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{27}
}

func (x *TcpInfo) GetTotalRetrans() uint32 {
	if x != nil {
		return x.TotalRetrans
	}
	return 0
}

func (x *TcpInfo) GetLost() uint32 {
	if x != nil {
		return x.Lost
	}
	return 0
}

func (x *TcpInfo) GetRttUs() uint32 {
	if x != nil {
		return x.RttUs
	}
	return 0
}

func (x *TcpInfo) GetRttvarUs() uint32 {
	if x != nil {
		return x.RttvarUs
	}
	return 0
}

func (x *TcpInfo) GetSndCwnd() uint32 {
	if x != nil {
		return x.SndCwnd
	}
	return 0
}

func (x *TcpInfo) GetSndSsthresh() uint32 {
	if x != nil {
		return x.SndSsthresh
	}
	return 0
}

var File_proto_loom_v1_control_proto protoreflect.FileDescriptor

const file_proto_loom_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/loom/v1/control.proto\x12\aloom.v1\x1a\x1egoogle/protobuf/duration.proto\"\x0f\n" +
	"\rHealthRequest\"a\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\rR\n" +
	"apiVersion\"}\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\rR\n" +
	"apiVersion\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"\x15\n" +
	"\x13CapabilitiesRequest\"\xb3\x02\n" +
	"\x14CapabilitiesResponse\x12\x1c\n" +
	"\tdatapaths\x18\x01 \x03(\tR\tdatapaths\x12\x1e\n" +
	"\n" +
	"generators\x18\x02 \x03(\tR\n" +
	"generators\x12\x1e\n" +
	"\n" +
	"schedulers\x18\x03 \x03(\tR\n" +
	"schedulers\x12\x1a\n" +
	"\bpayloads\x18\x04 \x03(\tR\bpayloads\x12/\n" +
	"\x13hardware_timestamps\x18\x05 \x01(\bR\x12hardwareTimestamps\x12\x1a\n" +
	"\bnetworks\x18\x06 \x03(\tR\bnetworks\x12\x12\n" +
	"\x04apps\x18\a \x03(\tR\x04apps\x12\x1f\n" +
	"\vapps_client\x18\b \x03(\tR\n" +
	"appsClient\x12\x1f\n" +
	"\vapps_server\x18\t \x03(\tR\n" +
	"appsServer\"\xf5\x04\n" +
	"\bFlowSpec\x12\x1c\n" +
	"\tgenerator\x18\x01 \x01(\tR\tgenerator\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1a\n" +
	"\bdatapath\x18\x03 \x01(\tR\bdatapath\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1f\n" +
	"\vpacket_size\x18\x05 \x01(\rR\n" +
	"packetSize\x12\x12\n" +
	"\x04rate\x18\x06 \x01(\tR\x04rate\x12\x14\n" +
	"\x05iface\x18\a \x01(\tR\x05iface\x12\x14\n" +
	"\x05queue\x18\b \x01(\rR\x05queue\x12\x1c\n" +
	"\temulation\x18\t \x01(\tR\temulation\x125\n" +
	"\bduration\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x14\n" +
	"\x05count\x18\v \x01(\x04R\x05count\x12\x16\n" +
	"\x06volume\x18\f \x01(\x04R\x06volume\x125\n" +
	"\x06params\x18\r \x03(\v2\x1d.loom.v1.FlowSpec.ParamsEntryR\x06params\x12\x12\n" +
	"\x04seed\x18\x0e \x01(\x03R\x04seed\x12\x1c\n" +
	"\ttransport\x18\x0f \x01(\tR\ttransport\x12\x10\n" +
	"\x03app\x18\x10 \x01(\tR\x03app\x12\x18\n" +
	"\anetwork\x18\x11 \x01(\tR\anetwork\x12\x14\n" +
	"\x05local\x18\x12 \x01(\tR\x05local\x12%\n" +
	"\x04role\x18\x15 \x01(\x0e2\x11.loom.v1.FlowRoleR\x04role\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x14\x10\x15R\x06listen\"9\n" +
	"\x10ConfigureRequest\x12%\n" +
	"\x04flow\x18\x01 \x01(\v2\x11.loom.v1.FlowSpecR\x04flow\"I\n" +
	"\x11ConfigureResponse\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x1b\n" +
	"\tdata_port\x18\x02 \x01(\rR\bdataPort\"%\n" +
	"\n" +
	"ArmRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\r\n" +
	"\vArmResponse\"\x8a\x01\n" +
	"\fStartRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12-\n" +
	"\x13start_at_unix_nanos\x18\x02 \x01(\x03R\x10startAtUnixNanos\x122\n" +
	"\x15report_interval_nanos\x18\x03 \x01(\x03R\x13reportIntervalNanos\"\x0f\n" +
	"\rStartResponse\"&\n" +
	"\vStopRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\x0e\n" +
	"\fStopResponse\")\n" +
	"\x0eDestroyRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\x11\n" +
	"\x0fDestroyResponse\"!\n" +
	"\x0fTimeSyncRequest\x12\x0e\n" +
	"\x02t1\x18\x01 \x01(\x03R\x02t1\"B\n" +
	"\x10TimeSyncResponse\x12\x0e\n" +
	"\x02t1\x18\x01 \x01(\x03R\x02t1\x12\x0e\n" +
	"\x02t2\x18\x02 \x01(\x03R\x02t2\x12\x0e\n" +
	"\x02t3\x18\x03 \x01(\x03R\x02t3\"+\n" +
	"\x10TelemetryRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\x93\x03\n" +
	"\x0fTelemetrySample\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x03R\x05nanos\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x04R\x05bytes\x12\x18\n" +
	"\apackets\x18\x04 \x01(\x04R\apackets\x12 \n" +
	"\fbits_per_sec\x18\x05 \x01(\x01R\n" +
	"bitsPerSec\x12%\n" +
	"\x0einterval_index\x18\x06 \x01(\x03R\rintervalIndex\x12%\n" +
	"\x0einterval_bytes\x18\a \x01(\x04R\rintervalBytes\x12)\n" +
	"\x10interval_packets\x18\b \x01(\x04R\x0fintervalPackets\x12%\n" +
	"\x0einterval_nanos\x18\t \x01(\x03R\rintervalNanos\x12\x14\n" +
	"\x05final\x18\n" +
	" \x01(\bR\x05final\x12\"\n" +
	"\x03tcp\x18\v \x01(\v2\x10.loom.v1.TcpInfoR\x03tcp\x12%\n" +
	"\x03app\x18\f \x01(\v2\x13.loom.v1.AppMetricsR\x03app\"\x9b\x01\n" +
	"\n" +
	"AppMetrics\x12*\n" +
	"\x04voip\x18\x01 \x01(\v2\x14.loom.v1.VoipMetricsH\x00R\x04voip\x12*\n" +
	"\x04http\x18\x02 \x01(\v2\x14.loom.v1.HttpMetricsH\x00R\x04http\x12-\n" +
	"\x05video\x18\x03 \x01(\v2\x15.loom.v1.VideoMetricsH\x00R\x05videoB\x06\n" +
	"\x04kind\"\xcc\x03\n" +
	"\vVoipMetrics\x12\x15\n" +
	"\x06mos_cq\x18\x01 \x01(\x01R\x05mosCq\x12\x19\n" +
	"\br_factor\x18\x02 \x01(\x01R\arFactor\x12\x1b\n" +
	"\tjitter_ms\x18\x03 \x01(\x01R\bjitterMs\x12\x19\n" +
	"\bloss_pct\x18\x04 \x01(\x01R\alossPct\x12\x1f\n" +
	"\vdiscard_pct\x18\x05 \x01(\x01R\n" +
	"discardPct\x12\x17\n" +
	"\aburst_r\x18\x06 \x01(\x01R\x06burstR\x12\x15\n" +
	"\x06rtt_ms\x18\a \x01(\x01R\x05rttMs\x12\x15\n" +
	"\x06owd_ms\x18\b \x01(\x01R\x05owdMs\x12\x1c\n" +
	"\n" +
	"owd_err_ms\x18\t \x01(\x01R\bowdErrMs\x12\x1d\n" +
	"\n" +
	"owd_method\x18\n" +
	" \x01(\tR\towdMethod\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\v \x01(\x04R\trxPackets\x12\x12\n" +
	"\x04lost\x18\f \x01(\x04R\x04lost\x12%\n" +
	"\x04gaps\x18\r \x03(\v2\x11.loom.v1.MediaGapR\x04gaps\x12\"\n" +
	"\rremote_mos_cq\x18\x0e \x01(\x01R\vremoteMosCq\x120\n" +
	"\x06emodel\x18\x0f \x01(\v2\x18.loom.v1.EModelBreakdownR\x06emodel\"\x82\x01\n" +
	"\x0fEModelBreakdown\x12\x0e\n" +
	"\x02ro\x18\x01 \x01(\x01R\x02ro\x12\x0e\n" +
	"\x02is\x18\x02 \x01(\x01R\x02is\x12\x12\n" +
	"\x04idte\x18\x03 \x01(\x01R\x04idte\x12\x12\n" +
	"\x04idle\x18\x04 \x01(\x01R\x04idle\x12\x10\n" +
	"\x03idd\x18\x05 \x01(\x01R\x03idd\x12\x15\n" +
	"\x06ie_eff\x18\x06 \x01(\x01R\x05ieEff\"}\n" +
	"\bMediaGap\x12(\n" +
	"\x10start_unix_nanos\x18\x01 \x01(\x03R\x0estartUnixNanos\x12$\n" +
	"\x0eend_unix_nanos\x18\x02 \x01(\x03R\fendUnixNanos\x12!\n" +
	"\fpackets_lost\x18\x03 \x01(\rR\vpacketsLost\"\xcd\x01\n" +
	"\vHttpMetrics\x12\x1a\n" +
	"\brequests\x18\x01 \x01(\x04R\brequests\x12\x16\n" +
	"\x06errors\x18\x02 \x01(\x04R\x06errors\x12\x1e\n" +
	"\vttfb_ms_p95\x18\x03 \x01(\x01R\tttfbMsP95\x12!\n" +
	"\fgoodput_mbps\x18\x04 \x01(\x01R\vgoodputMbps\x12(\n" +
	"\x10tls_handshake_ms\x18\x05 \x01(\x01R\x0etlsHandshakeMs\x12\x1d\n" +
	"\n" +
	"connect_ms\x18\x06 \x01(\x01R\tconnectMs\"\x8d\x02\n" +
	"\fVideoMetrics\x12\x16\n" +
	"\x06stalls\x18\x01 \x01(\x04R\x06stalls\x12\"\n" +
	"\rstall_time_ms\x18\x02 \x01(\x01R\vstallTimeMs\x12%\n" +
	"\x0erebuffer_ratio\x18\x03 \x01(\x01R\rrebufferRatio\x12\x1b\n" +
	"\tbuffer_ms\x18\x04 \x01(\x01R\bbufferMs\x12(\n" +
	"\x10avg_bitrate_kbps\x18\x05 \x01(\x01R\x0eavgBitrateKbps\x12\x1d\n" +
	"\n" +
	"startup_ms\x18\x06 \x01(\x01R\tstartupMs\x124\n" +
	"\fstall_events\x18\a \x03(\v2\x11.loom.v1.MediaGapR\vstallEvents\"\xb4\x01\n" +
	"\aTcpInfo\x12#\n" +
	"\rtotal_retrans\x18\x01 \x01(\rR\ftotalRetrans\x12\x12\n" +
	"\x04lost\x18\x02 \x01(\rR\x04lost\x12\x15\n" +
	"\x06rtt_us\x18\x03 \x01(\rR\x05rttUs\x12\x1b\n" +
	"\trttvar_us\x18\x04 \x01(\rR\brttvarUs\x12\x19\n" +
	"\bsnd_cwnd\x18\x05 \x01(\rR\asndCwnd\x12!\n" +
	"\fsnd_ssthresh\x18\x06 \x01(\rR\vsndSsthresh*\xd2\x01\n" +
	"\bFlowRole\x12\x19\n" +
	"\x15FLOW_ROLE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10FLOW_ROLE_SENDER\x10\x01\x12\x16\n" +
	"\x12FLOW_ROLE_RECEIVER\x10\x02\x12\x17\n" +
	"\x13FLOW_ROLE_REFLECTOR\x10\x03\x12\x17\n" +
	"\x13FLOW_ROLE_RESPONDER\x10\x04\x12\x17\n" +
	"\x13FLOW_ROLE_REQUESTER\x10\x05\x12\x18\n" +
	"\x14FLOW_ROLE_APP_CLIENT\x10\x06\x12\x18\n" +
	"\x14FLOW_ROLE_APP_SERVER\x10\a2\xfe\x04\n" +
	"\aControl\x129\n" +
	"\x06Health\x12\x16.loom.v1.HealthRequest\x1a\x17.loom.v1.HealthResponse\x12?\n" +
	"\bRegister\x12\x18.loom.v1.RegisterRequest\x1a\x19.loom.v1.RegisterResponse\x12K\n" +
	"\fCapabilities\x12\x1c.loom.v1.CapabilitiesRequest\x1a\x1d.loom.v1.CapabilitiesResponse\x12B\n" +
	"\tConfigure\x12\x19.loom.v1.ConfigureRequest\x1a\x1a.loom.v1.ConfigureResponse\x120\n" +
	"\x03Arm\x12\x13.loom.v1.ArmRequest\x1a\x14.loom.v1.ArmResponse\x126\n" +
	"\x05Start\x12\x15.loom.v1.StartRequest\x1a\x16.loom.v1.StartResponse\x123\n" +
	"\x04Stop\x12\x14.loom.v1.StopRequest\x1a\x15.loom.v1.StopResponse\x12<\n" +
	"\aDestroy\x12\x17.loom.v1.DestroyRequest\x1a\x18.loom.v1.DestroyResponse\x12?\n" +
	"\bTimeSync\x12\x18.loom.v1.TimeSyncRequest\x1a\x19.loom.v1.TimeSyncResponse\x12H\n" +
	"\x0fStreamTelemetry\x12\x19.loom.v1.TelemetryRequest\x1a\x18.loom.v1.TelemetrySample0\x01B,Z*github.com/bgrewell/loom/api/loomv1;loomv1b\x06proto3"

var (
	file_proto_loom_v1_control_proto_rawDescOnce sync.Once
	file_proto_loom_v1_control_proto_rawDescData []byte
)

func file_proto_loom_v1_control_proto_rawDescGZIP() []byte {
	file_proto_loom_v1_control_proto_rawDescOnce.Do(func() {
		file_proto_loom_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_loom_v1_control_proto_rawDesc), len(file_proto_loom_v1_control_proto_rawDesc)))
	})
	return file_proto_loom_v1_control_proto_rawDescData
}

var file_proto_loom_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_loom_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_loom_v1_control_proto_goTypes = []any{
	(FlowRole)(0),                // 0: loom.v1.FlowRole
	(*HealthRequest)(nil),        // 1: loom.v1.HealthRequest
	(*HealthResponse)(nil),       // 2: loom.v1.HealthResponse
	(*RegisterRequest)(nil),      // 3: loom.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 4: loom.v1.RegisterResponse
	(*CapabilitiesRequest)(nil),  // 5: loom.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 6: loom.v1.CapabilitiesResponse
	(*FlowSpec)(nil),             // 7: loom.v1.FlowSpec
	(*ConfigureRequest)(nil),     // 8: loom.v1.ConfigureRequest
	(*ConfigureResponse)(nil),    // 9: loom.v1.ConfigureResponse
	(*ArmRequest)(nil),           // 10: loom.v1.ArmRequest
	(*ArmResponse)(nil),          // 11: loom.v1.ArmResponse
	(*StartRequest)(nil),         // 12: loom.v1.StartRequest
	(*StartResponse)(nil),        // 13: loom.v1.StartResponse
	(*StopRequest)(nil),          // 14: loom.v1.StopRequest
	(*StopResponse)(nil),         // 15: loom.v1.StopResponse
	(*DestroyRequest)(nil),       // 16: loom.v1.DestroyRequest
	(*DestroyResponse)(nil),      // 17: loom.v1.DestroyResponse
	(*TimeSyncRequest)(nil),      // 18: loom.v1.TimeSyncRequest
	(*TimeSyncResponse)(nil),     // 19: loom.v1.TimeSyncResponse
	(*TelemetryRequest)(nil),     // 20: loom.v1.TelemetryRequest
	(*TelemetrySample)(nil),      // 21: loom.v1.TelemetrySample
	(*AppMetrics)(nil),           // 22: loom.v1.AppMetrics
	(*VoipMetrics)(nil),          // 23: loom.v1.VoipMetrics
	(*EModelBreakdown)(nil),      // 24: loom.v1.EModelBreakdown
	(*MediaGap)(nil),             // 25: loom.v1.MediaGap
	(*HttpMetrics)(nil),          // 26: loom.v1.HttpMetrics
	(*VideoMetrics)(nil),         // 27: loom.v1.VideoMetrics
	(*TcpInfo)(nil),              // 28: loom.v1.TcpInfo
	nil,                          // 29: loom.v1.FlowSpec.ParamsEntry
	(*durationpb.Duration)(nil),  // 30: google.protobuf.Duration
}
var file_proto_loom_v1_control_proto_depIdxs = []int32{
	30, // 0: loom.v1.FlowSpec.duration:type_name -> google.protobuf.Duration
	29, // 1: loom.v1.FlowSpec.params:type_name -> loom.v1.FlowSpec.ParamsEntry
	0,  // 2: loom.v1.FlowSpec.role:type_name -> loom.v1.FlowRole
	7,  // 3: loom.v1.ConfigureRequest.flow:type_name -> loom.v1.FlowSpec
	28, // 4: loom.v1.TelemetrySample.tcp:type_name -> loom.v1.TcpInfo
	22, // 5: loom.v1.TelemetrySample.app:type_name -> loom.v1.AppMetrics
	23, // 6: loom.v1.AppMetrics.voip:type_name -> loom.v1.VoipMetrics
	26, // 7: loom.v1.AppMetrics.http:type_name -> loom.v1.HttpMetrics
	27, // 8: loom.v1.AppMetrics.video:type_name -> loom.v1.VideoMetrics
	25, // 9: loom.v1.VoipMetrics.gaps:type_name -> loom.v1.MediaGap
	24, // 10: loom.v1.VoipMetrics.emodel:type_name -> loom.v1.EModelBreakdown
	25, // 11: loom.v1.VideoMetrics.stall_events:type_name -> loom.v1.MediaGap
	1,  // 12: loom.v1.Control.Health:input_type -> loom.v1.HealthRequest
	3,  // 13: loom.v1.Control.Register:input_type -> loom.v1.RegisterRequest
	5,  // 14: loom.v1.Control.Capabilities:input_type -> loom.v1.CapabilitiesRequest
	8,  // 15: loom.v1.Control.Configure:input_type -> loom.v1.ConfigureRequest
	10, // 16: loom.v1.Control.Arm:input_type -> loom.v1.ArmRequest
	12, // 17: loom.v1.Control.Start:input_type -> loom.v1.StartRequest
	14, // 18: loom.v1.Control.Stop:input_type -> loom.v1.StopRequest
	16, // 19: loom.v1.Control.Destroy:input_type -> loom.v1.DestroyRequest
	18, // 20: loom.v1.Control.TimeSync:input_type -> loom.v1.TimeSyncRequest
	20, // 21: loom.v1.Control.StreamTelemetry:input_type -> loom.v1.TelemetryRequest
	2,  // 22: loom.v1.Control.Health:output_type -> loom.v1.HealthResponse
	4,  // 23: loom.v1.Control.Register:output_type -> loom.v1.RegisterResponse
	6,  // 24: loom.v1.Control.Capabilities:output_type -> loom.v1.CapabilitiesResponse
	9,  // 25: loom.v1.Control.Configure:output_type -> loom.v1.ConfigureResponse
	11, // 26: loom.v1.Control.Arm:output_type -> loom.v1.ArmResponse
	13, // 27: loom.v1.Control.Start:output_type -> loom.v1.StartResponse
	15, // 28: loom.v1.Control.Stop:output_type -> loom.v1.StopResponse
	17, // 29: loom.v1.Control.Destroy:output_type -> loom.v1.DestroyResponse
	19, // 30: loom.v1.Control.TimeSync:output_type -> loom.v1.TimeSyncResponse
	21, // 31: loom.v1.Control.StreamTelemetry:output_type -> loom.v1.TelemetrySample
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_loom_v1_control_proto_init() }
func file_proto_loom_v1_control_proto_init() {
	if File_proto_loom_v1_control_proto != nil {
		return
	}
	file_proto_loom_v1_control_proto_msgTypes[21].OneofWrappers = []any{
		(*AppMetrics_Voip)(nil),
		(*AppMetrics_Http)(nil),
		(*AppMetrics_Video)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_loom_v1_control_proto_rawDesc), len(file_proto_loom_v1_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_loom_v1_control_proto_goTypes,
		DependencyIndexes: file_proto_loom_v1_control_proto_depIdxs,
		EnumInfos:         file_proto_loom_v1_control_proto_enumTypes,
		MessageInfos:      file_proto_loom_v1_control_proto_msgTypes,
	}.Build()
	File_proto_loom_v1_control_proto = out.File
	file_proto_loom_v1_control_proto_goTypes = nil
	file_proto_loom_v1_control_proto_depIdxs = nil
}
