// Copyright 2026 Benjamin Grewell
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/loom/v1/control.proto

package loomv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{4}
}

type CapabilitiesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Datapaths          []string               `protobuf:"bytes,1,rep,name=datapaths,proto3" json:"datapaths,omitempty"`
	Generators         []string               `protobuf:"bytes,2,rep,name=generators,proto3" json:"generators,omitempty"`
	Schedulers         []string               `protobuf:"bytes,3,rep,name=schedulers,proto3" json:"schedulers,omitempty"`
	Payloads           []string               `protobuf:"bytes,4,rep,name=payloads,proto3" json:"payloads,omitempty"`
	HardwareTimestamps bool                   `protobuf:"varint,5,opt,name=hardware_timestamps,json=hardwareTimestamps,proto3" json:"hardware_timestamps,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilitiesResponse) GetDatapaths() []string {
	if x != nil {
		return x.Datapaths
	}
	return nil
}

func (x *CapabilitiesResponse) GetGenerators() []string {
	if x != nil {
		return x.Generators
	}
	return nil
}

func (x *CapabilitiesResponse) GetSchedulers() []string {
	if x != nil {
		return x.Schedulers
	}
	return nil
}

func (x *CapabilitiesResponse) GetPayloads() []string {
	if x != nil {
		return x.Payloads
	}
	return nil
}

func (x *CapabilitiesResponse) GetHardwareTimestamps() bool {
	if x != nil {
		return x.HardwareTimestamps
	}
	return false
}

// FlowSpec describes one flow to run, mirroring `loom run` flags.
type FlowSpec struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Generator  string                 `protobuf:"bytes,1,opt,name=generator,proto3" json:"generator,omitempty"`
	Payload    string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Datapath   string                 `protobuf:"bytes,3,opt,name=datapath,proto3" json:"datapath,omitempty"`
	Target     string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"` // host:port for udp/tcp
	PacketSize uint32                 `protobuf:"varint,5,opt,name=packet_size,json=packetSize,proto3" json:"packet_size,omitempty"`
	Rate       string                 `protobuf:"bytes,6,opt,name=rate,proto3" json:"rate,omitempty"` // e.g. "100Mbps"; empty = unlimited
	// Stop condition (whichever is reached first; all empty = until-stopped).
	Duration string `protobuf:"bytes,10,opt,name=duration,proto3" json:"duration,omitempty"` // e.g. "10s"
	Count    uint64 `protobuf:"varint,11,opt,name=count,proto3" json:"count,omitempty"`      // packets
	Volume   uint64 `protobuf:"varint,12,opt,name=volume,proto3" json:"volume,omitempty"`    // bytes
	// listen makes this a receiver: the agent binds an ephemeral UDP port,
	// returned as ConfigureResponse.data_port, and drains+accounts inbound packets
	// instead of generating.
	Listen        bool `protobuf:"varint,20,opt,name=listen,proto3" json:"listen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowSpec) Reset() {
	*x = FlowSpec{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSpec) ProtoMessage() {}

func (x *FlowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSpec.ProtoReflect.Descriptor instead.
func (*FlowSpec) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *FlowSpec) GetGenerator() string {
	if x != nil {
		return x.Generator
	}
	return ""
}

func (x *FlowSpec) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *FlowSpec) GetDatapath() string {
	if x != nil {
		return x.Datapath
	}
	return ""
}

func (x *FlowSpec) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FlowSpec) GetPacketSize() uint32 {
	if x != nil {
		return x.PacketSize
	}
	return 0
}

func (x *FlowSpec) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *FlowSpec) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *FlowSpec) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FlowSpec) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *FlowSpec) GetListen() bool {
	if x != nil {
		return x.Listen
	}
	return false
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flow          *FlowSpec              `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureRequest) GetFlow() *FlowSpec {
	if x != nil {
		return x.Flow
	}
	return nil
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	DataPort      uint32                 `protobuf:"varint,2,opt,name=data_port,json=dataPort,proto3" json:"data_port,omitempty"` // ephemeral port the agent will listen/send on
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigureResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ConfigureResponse) GetDataPort() uint32 {
	if x != nil {
		return x.DataPort
	}
	return 0
}

type ArmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmRequest) Reset() {
	*x = ArmRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmRequest) ProtoMessage() {}

func (x *ArmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmRequest.ProtoReflect.Descriptor instead.
func (*ArmRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ArmRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type ArmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmResponse) Reset() {
	*x = ArmResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmResponse) ProtoMessage() {}

func (x *ArmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmResponse.ProtoReflect.Descriptor instead.
func (*ArmResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{10}
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{11}
}

func (x *StartRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type StartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{12}
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *StopRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{14}
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *DestroyRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{16}
}

// TimeSync four-timestamp exchange: client stamps t1, server stamps t2 (recv)
// and t3 (send), client stamps t4 on receipt.
type TimeSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T1            int64                  `protobuf:"varint,1,opt,name=t1,proto3" json:"t1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSyncRequest) Reset() {
	*x = TimeSyncRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncRequest) ProtoMessage() {}

func (x *TimeSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncRequest.ProtoReflect.Descriptor instead.
func (*TimeSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *TimeSyncRequest) GetT1() int64 {
	if x != nil {
		return x.T1
	}
	return 0
}

type TimeSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T1            int64                  `protobuf:"varint,1,opt,name=t1,proto3" json:"t1,omitempty"`
	T2            int64                  `protobuf:"varint,2,opt,name=t2,proto3" json:"t2,omitempty"`
	T3            int64                  `protobuf:"varint,3,opt,name=t3,proto3" json:"t3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSyncResponse) Reset() {
	*x = TimeSyncResponse{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSyncResponse) ProtoMessage() {}

func (x *TimeSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSyncResponse.ProtoReflect.Descriptor instead.
func (*TimeSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *TimeSyncResponse) GetT1() int64 {
	if x != nil {
		return x.T1
	}
	return 0
}

func (x *TimeSyncResponse) GetT2() int64 {
	if x != nil {
		return x.T2
	}
	return 0
}

func (x *TimeSyncResponse) GetT3() int64 {
	if x != nil {
		return x.T3
	}
	return 0
}

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"` // empty = all flows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *TelemetryRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type TelemetrySample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Nanos         int64                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	Bytes         uint64                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Packets       uint64                 `protobuf:"varint,4,opt,name=packets,proto3" json:"packets,omitempty"`
	BitsPerSec    float64                `protobuf:"fixed64,5,opt,name=bits_per_sec,json=bitsPerSec,proto3" json:"bits_per_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySample) Reset() {
	*x = TelemetrySample{}
	mi := &file_proto_loom_v1_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySample) ProtoMessage() {}

func (x *TelemetrySample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_loom_v1_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySample.ProtoReflect.Descriptor instead.
func (*TelemetrySample) Descriptor() ([]byte, []int) {
	return file_proto_loom_v1_control_proto_rawDescGZIP(), []int{20}
}

func (x *TelemetrySample) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *TelemetrySample) GetNanos() int64 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

func (x *TelemetrySample) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *TelemetrySample) GetPackets() uint64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *TelemetrySample) GetBitsPerSec() float64 {
	if x != nil {
		return x.BitsPerSec
	}
	return 0
}

var File_proto_loom_v1_control_proto protoreflect.FileDescriptor

const file_proto_loom_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/loom/v1/control.proto\x12\aloom.v1\"\x0f\n" +
	"\rHealthRequest\"@\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\"\\\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"\x15\n" +
	"\x13CapabilitiesRequest\"\xc1\x01\n" +
	"\x14CapabilitiesResponse\x12\x1c\n" +
	"\tdatapaths\x18\x01 \x03(\tR\tdatapaths\x12\x1e\n" +
	"\n" +
	"generators\x18\x02 \x03(\tR\n" +
	"generators\x12\x1e\n" +
	"\n" +
	"schedulers\x18\x03 \x03(\tR\n" +
	"schedulers\x12\x1a\n" +
	"\bpayloads\x18\x04 \x03(\tR\bpayloads\x12/\n" +
	"\x13hardware_timestamps\x18\x05 \x01(\bR\x12hardwareTimestamps\"\x8d\x02\n" +
	"\bFlowSpec\x12\x1c\n" +
	"\tgenerator\x18\x01 \x01(\tR\tgenerator\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1a\n" +
	"\bdatapath\x18\x03 \x01(\tR\bdatapath\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1f\n" +
	"\vpacket_size\x18\x05 \x01(\rR\n" +
	"packetSize\x12\x12\n" +
	"\x04rate\x18\x06 \x01(\tR\x04rate\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\tR\bduration\x12\x14\n" +
	"\x05count\x18\v \x01(\x04R\x05count\x12\x16\n" +
	"\x06volume\x18\f \x01(\x04R\x06volume\x12\x16\n" +
	"\x06listen\x18\x14 \x01(\bR\x06listen\"9\n" +
	"\x10ConfigureRequest\x12%\n" +
	"\x04flow\x18\x01 \x01(\v2\x11.loom.v1.FlowSpecR\x04flow\"I\n" +
	"\x11ConfigureResponse\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x1b\n" +
	"\tdata_port\x18\x02 \x01(\rR\bdataPort\"%\n" +
	"\n" +
	"ArmRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\r\n" +
	"\vArmResponse\"'\n" +
	"\fStartRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\x0f\n" +
	"\rStartResponse\"&\n" +
	"\vStopRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\x0e\n" +
	"\fStopResponse\")\n" +
	"\x0eDestroyRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\x11\n" +
	"\x0fDestroyResponse\"!\n" +
	"\x0fTimeSyncRequest\x12\x0e\n" +
	"\x02t1\x18\x01 \x01(\x03R\x02t1\"B\n" +
	"\x10TimeSyncResponse\x12\x0e\n" +
	"\x02t1\x18\x01 \x01(\x03R\x02t1\x12\x0e\n" +
	"\x02t2\x18\x02 \x01(\x03R\x02t2\x12\x0e\n" +
	"\x02t3\x18\x03 \x01(\x03R\x02t3\"+\n" +
	"\x10TelemetryRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\"\x92\x01\n" +
	"\x0fTelemetrySample\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x03R\x05nanos\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x04R\x05bytes\x12\x18\n" +
	"\apackets\x18\x04 \x01(\x04R\apackets\x12 \n" +
	"\fbits_per_sec\x18\x05 \x01(\x01R\n" +
	"bitsPerSec2\xfe\x04\n" +
	"\aControl\x129\n" +
	"\x06Health\x12\x16.loom.v1.HealthRequest\x1a\x17.loom.v1.HealthResponse\x12?\n" +
	"\bRegister\x12\x18.loom.v1.RegisterRequest\x1a\x19.loom.v1.RegisterResponse\x12K\n" +
	"\fCapabilities\x12\x1c.loom.v1.CapabilitiesRequest\x1a\x1d.loom.v1.CapabilitiesResponse\x12B\n" +
	"\tConfigure\x12\x19.loom.v1.ConfigureRequest\x1a\x1a.loom.v1.ConfigureResponse\x120\n" +
	"\x03Arm\x12\x13.loom.v1.ArmRequest\x1a\x14.loom.v1.ArmResponse\x126\n" +
	"\x05Start\x12\x15.loom.v1.StartRequest\x1a\x16.loom.v1.StartResponse\x123\n" +
	"\x04Stop\x12\x14.loom.v1.StopRequest\x1a\x15.loom.v1.StopResponse\x12<\n" +
	"\aDestroy\x12\x17.loom.v1.DestroyRequest\x1a\x18.loom.v1.DestroyResponse\x12?\n" +
	"\bTimeSync\x12\x18.loom.v1.TimeSyncRequest\x1a\x19.loom.v1.TimeSyncResponse\x12H\n" +
	"\x0fStreamTelemetry\x12\x19.loom.v1.TelemetryRequest\x1a\x18.loom.v1.TelemetrySample0\x01B,Z*github.com/bgrewell/loom/api/loomv1;loomv1b\x06proto3"

var (
	file_proto_loom_v1_control_proto_rawDescOnce sync.Once
	file_proto_loom_v1_control_proto_rawDescData []byte
)

func file_proto_loom_v1_control_proto_rawDescGZIP() []byte {
	file_proto_loom_v1_control_proto_rawDescOnce.Do(func() {
		file_proto_loom_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_loom_v1_control_proto_rawDesc), len(file_proto_loom_v1_control_proto_rawDesc)))
	})
	return file_proto_loom_v1_control_proto_rawDescData
}

var file_proto_loom_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_loom_v1_control_proto_goTypes = []any{
	(*HealthRequest)(nil),        // 0: loom.v1.HealthRequest
	(*HealthResponse)(nil),       // 1: loom.v1.HealthResponse
	(*RegisterRequest)(nil),      // 2: loom.v1.RegisterRequest
	(*RegisterResponse)(nil),     // 3: loom.v1.RegisterResponse
	(*CapabilitiesRequest)(nil),  // 4: loom.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 5: loom.v1.CapabilitiesResponse
	(*FlowSpec)(nil),             // 6: loom.v1.FlowSpec
	(*ConfigureRequest)(nil),     // 7: loom.v1.ConfigureRequest
	(*ConfigureResponse)(nil),    // 8: loom.v1.ConfigureResponse
	(*ArmRequest)(nil),           // 9: loom.v1.ArmRequest
	(*ArmResponse)(nil),          // 10: loom.v1.ArmResponse
	(*StartRequest)(nil),         // 11: loom.v1.StartRequest
	(*StartResponse)(nil),        // 12: loom.v1.StartResponse
	(*StopRequest)(nil),          // 13: loom.v1.StopRequest
	(*StopResponse)(nil),         // 14: loom.v1.StopResponse
	(*DestroyRequest)(nil),       // 15: loom.v1.DestroyRequest
	(*DestroyResponse)(nil),      // 16: loom.v1.DestroyResponse
	(*TimeSyncRequest)(nil),      // 17: loom.v1.TimeSyncRequest
	(*TimeSyncResponse)(nil),     // 18: loom.v1.TimeSyncResponse
	(*TelemetryRequest)(nil),     // 19: loom.v1.TelemetryRequest
	(*TelemetrySample)(nil),      // 20: loom.v1.TelemetrySample
}
var file_proto_loom_v1_control_proto_depIdxs = []int32{
	6,  // 0: loom.v1.ConfigureRequest.flow:type_name -> loom.v1.FlowSpec
	0,  // 1: loom.v1.Control.Health:input_type -> loom.v1.HealthRequest
	2,  // 2: loom.v1.Control.Register:input_type -> loom.v1.RegisterRequest
	4,  // 3: loom.v1.Control.Capabilities:input_type -> loom.v1.CapabilitiesRequest
	7,  // 4: loom.v1.Control.Configure:input_type -> loom.v1.ConfigureRequest
	9,  // 5: loom.v1.Control.Arm:input_type -> loom.v1.ArmRequest
	11, // 6: loom.v1.Control.Start:input_type -> loom.v1.StartRequest
	13, // 7: loom.v1.Control.Stop:input_type -> loom.v1.StopRequest
	15, // 8: loom.v1.Control.Destroy:input_type -> loom.v1.DestroyRequest
	17, // 9: loom.v1.Control.TimeSync:input_type -> loom.v1.TimeSyncRequest
	19, // 10: loom.v1.Control.StreamTelemetry:input_type -> loom.v1.TelemetryRequest
	1,  // 11: loom.v1.Control.Health:output_type -> loom.v1.HealthResponse
	3,  // 12: loom.v1.Control.Register:output_type -> loom.v1.RegisterResponse
	5,  // 13: loom.v1.Control.Capabilities:output_type -> loom.v1.CapabilitiesResponse
	8,  // 14: loom.v1.Control.Configure:output_type -> loom.v1.ConfigureResponse
	10, // 15: loom.v1.Control.Arm:output_type -> loom.v1.ArmResponse
	12, // 16: loom.v1.Control.Start:output_type -> loom.v1.StartResponse
	14, // 17: loom.v1.Control.Stop:output_type -> loom.v1.StopResponse
	16, // 18: loom.v1.Control.Destroy:output_type -> loom.v1.DestroyResponse
	18, // 19: loom.v1.Control.TimeSync:output_type -> loom.v1.TimeSyncResponse
	20, // 20: loom.v1.Control.StreamTelemetry:output_type -> loom.v1.TelemetrySample
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_loom_v1_control_proto_init() }
func file_proto_loom_v1_control_proto_init() {
	if File_proto_loom_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_loom_v1_control_proto_rawDesc), len(file_proto_loom_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_loom_v1_control_proto_goTypes,
		DependencyIndexes: file_proto_loom_v1_control_proto_depIdxs,
		MessageInfos:      file_proto_loom_v1_control_proto_msgTypes,
	}.Build()
	File_proto_loom_v1_control_proto = out.File
	file_proto_loom_v1_control_proto_goTypes = nil
	file_proto_loom_v1_control_proto_depIdxs = nil
}
